Update arrow version from 9 to 14
* Set C+ standard+ to 17 to accommodate arrow build. `flightsql-odbc` used C++ 11, but arrow 14.0.0 uses C++ 17,  so C++ standard is set to 17 to support building of arrow.
* Error arrow/utils/optional.h no longer found is fixed.
    * I found that [Arrow commit 5e49174](https://github.com/apache/arrow/commit/5e49174d69deb9d1cbbdf82bc8041b90098f560b)
removes arrow/utils/optional.h and replaces it with <optional> C++ 17 header.
So I updated flightsql-odbc code with when looking at this commit.
* Removed deprecated `std::binary_function`.
* There are build errors from `boost::variant`, so changed `boost::variant` to `std::variant` to align with rest of Arrow repository. Also replaced `boost::get` with `std::get` as a result.
* Fixed "error C2660: 'arrow::flight::FlightInfo::GetSchema': function does not take 2 arguments":
I checked [commit d214455c2179f8ba15bcdce48f36bcb123b47123](https://github.com/apache/arrow/commit/d214455c2179f8ba15bcdce48f36bcb123b47123)
that changed GetSchema, and found that GetSchema(dictionary_memo, out) can be replaced with GetSchema(dictionary_memo).Value(out).
* Fixed error C2661: 'arrow::flight::FlightClient::Connect': no overloaded function takes 3 arguments:
I checked [commit 9e08c503f97fe3848039c80ec07e324db7dfbadf](https://github.com/apache/arrow/commit/9e08c503f97fe3848039c80ec07e324db7dfbadf)
that changed Connect, and found that Connect(location, options, client) can be replaced with Connect(location, options).Value(client).
* Fixed error C2660: 'arrow::flight::Location::ForGrpcTls': function does not take 3 arguments:
I checked [commit d214455c2179f8ba15bcdce48f36bcb123b47123](https://github.com/apache/arrow/commit/d214455c2179f8ba15bcdce48f36bcb123b47123)
that changed ForGrpcTls, and found that Connect(host, port, location) can be replaced with ForGrpcTls(host, port).Value(location). Same process to fix error with `Location::ForGrpcTcp`.
* Fixed error of scalar->value being deprecated. I see from [commit 6cc37cf2d1ba72c46b64fbc7ac499bd0d7296d20](https://github.com/apache/arrow/commit/6cc37cf2d1ba72c46b64fbc7ac499bd0d7296d20)
that scalar::value is replaced with scalar::child_value(), so I went with this change.
* Fixed linking errors. `ARROW_FLIGHT_SQL_STATIC` was added in [commit 9c93f82a06ecae4d0e51f64b25fc63d32701d734](https://github.com/apache/arrow/commit/9c93f82a06ecae4d0e51f64b25fc63d32701d734), so now we need to define `ARROW_FLIGHT_SQL_STATIC` in CMakeLists.txt also.